name: Update Spotify Status

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Spotify SVG
        uses: novatorem/novatorem@master
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md || true
          git commit -m "chore: update spotify status" || true
          git push || true
